version: "3.9"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sysdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  products-service:
    build:
      context: ./Backend/products
    container_name: products-service
    ports:
      - "8081:8081"
    environment:
      PORT: 8081
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_NAME: sysdb
      DB_USER: appuser
      DB_PASSWORD: apppass
    depends_on:
      - mysql-db
    networks:
      - backend

  categories-service:
    build:
      context: ./Backend/categoria
    container_name: categories-service
    ports:
      - "8083:8083"
    environment:
      PORT: 8083
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_NAME: sysdb
      DB_USER: appuser
      DB_PASSWORD: apppass
    depends_on:
      - mysql-db
    networks:
      - backend

  frontend:
    build:
      context: ./FrontendSys
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - products-service
      - categories-service
    networks:
      - frontend
      - backend

networks:
  backend:
  frontend:

volumes:
  mysql_data:


# version: "3.9"

# services:
#   # -------------------
#   # Base de datos MySQL
#   # -------------------
#   mysql-db:
#     image: mysql:8.0
#     container_name: mysql-db
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: sysdb
#       MYSQL_USER: appuser
#       MYSQL_PASSWORD: apppass
#     ports:
#       - "3307:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql
#     networks:
#       - backend

#   # -------------------
#   # Microservicio Products
#   # -------------------
#   products-service:
#     build:
#       context: ./Backend/products
#     container_name: products-service
#     ports:
#       - "8081:8081"
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/sysdb
#       SPRING_DATASOURCE_USERNAME: appuser
#       SPRING_DATASOURCE_PASSWORD: apppass
#       SPRING_JPA_HIBERNATE_DDL_AUTO: update
#     depends_on:
#       - mysql-db
#     networks:
#       - backend

#   # -------------------
#   # Microservicio Categories
#   # -------------------
#   categories-service:
#     build:
#       context: ./Backend/categoria
#     container_name: categories-service
#     ports:
#       - "8083:8083"
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/sysdb
#       SPRING_DATASOURCE_USERNAME: appuser
#       SPRING_DATASOURCE_PASSWORD: apppass
#       SPRING_JPA_HIBERNATE_DDL_AUTO: update
#     depends_on:
#       - mysql-db
#     networks:
#       - backend

#   # -------------------
#   # Frontend Angular
#   # -------------------
#   frontend:
#     build:
#       context: ./FrontendSys
#       dockerfile: Dockerfile
#     container_name: frontend
#     ports:
#       - "4200:80"
#     depends_on:
#       - products-service
#       - categories-service
#     networks:
#       - frontend
#       - backend

# # -------------------
# # Redes y Volúmenes
# # -------------------
# networks:
#   backend:
#   frontend:

# volumes:
#   mysql_data:
